export const GAUTENG= [
    {
        id: 0,
        title: <a href="https://aadp.org.za/">Action Alliance Development Party (AADP)</a>,
        icon: "./Assets/Images/Party Logo/AADP.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 1,
        title: <a href="https://www.actionsa.org.za//">Action SA()</a>,
        icon: "./Assets/Images/Party Logo/ASA.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 2,
        title: "Africa Africans Reclaim (AAR)",
        icon: "./Assets/Images/Party Logo/AAR.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 3,
        title: <a href="https://ara-sa.org.za/">Africa Restoration Alliance (ARA)</a>,
        icon: "./Assets/Images/Party Logo/AAR.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 4,
        title: "African Christian Democratic Party",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 5,
        title: "African Congress for Transformation",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 6,
        title: <a href="https://africanheart.org.za/">African Heart Congress (AHC)</a>,
        icon: "./Assets/Images/Party Logo/AHC.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 7,
        title: "African Independent Congress (AIC)",
        icon: "./Assets/Images/Party Logo/AIC.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 8,    
        title: "African Independent Peoples Organizstion",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 9,
        title: "African Movement Congress",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 10,
        title: "African National Congress",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 11,
        title: "African People First (APF)",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 12,
        title: "African Peoples Convention",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 13,
        title: "African Transformation Movement",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 14,
        title: <a href="https://www.aljama.co.za/">Al-Jama-ah (AJA)</a>,
        icon: "./Assets/Images/Party Logo/ALJ.jpg",
        date: "02/03/2024",
        responsibility: [""],
    },
    {
        id: 15,
        title: <a href="https://accforchange.org.za/">Alliance of Citizens For Change</a>,
        icon: "./Assets/Images/Party Logo/A.C.C.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 16,
        title: <a href="https://am4c.org/">Allied Movement for Change (AM4C)</a>,
        icon: "./Assets/Images/Party Logo/AM4C.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 18,
        title: <a href="https://www.azania2024.org.za/">Azania Peaceful Revolution</a>,
        icon: "./Assets/Images/Party Logo/AADP.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 17,
        title: <a href="https://www.arisesa.org/">Arise South Africa</a>,
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 19,
        title: <a href="https://azapo.org.za/">Azanian Peoples Organization (AZAPO)</a>,
        icon: "./Assets/Images/Party Logo/AZAPO.jpeg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 20,
        title: "Basic Income Grant SA",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 21,
        title: "Bolsheviks Party of South Africa",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 22,
        title: "Build One South Africa",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 23,
        title: "Bongani Wellington Cibi (Indepedent)",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 24,
        title: "Congress of The People",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 25,
        title: "Democratic Alliance",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 26,
        title: "Economic Freedom Fighters",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 27,
        title: <a href="https://forum4sd.org.za/">Forum 4 Service Delivery (F4SD)</a>,
        icon: "./Assets/Images/Party Logo/F4SD.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 28,
        title: "GOOD",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {    
        id: 29,
        title: <a href="https://www.hope4sa.org.za/">#HOPE4SA</a>,
        icon: "./Assets/Images/Party Logo/H4SA.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 30,
        title: "Inkatha Freedom Party",
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    }, 
    {    
        id: 31,
        title: "Tshepo Johannes Mogano",
        icon: "./Assets/Images/Party Logo/H4SA.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 32,
        title: "National Freedom Party (NFP)",
        icon: "./Assets/Images/Party Logo/NFP.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 33,
        title: "Operation Dudula",
        icon: "./Assets/Images/Party Logo/AAR.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 34,
        title: <a href="https://pac.org.za/">Pan Africanist Congress of Azania (PAC)</a>,
        icon: "./Assets/Images/Party Logo/PAC.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 35,
        title: <a href="https://mypa.org.za/">Patriotic Alliance (PA)</a>,
        icon: "./Assets/Images/Party Logo/PA.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 36,
        title: <a href="https://www.risemzansi.org/">Rise Mzansi (RS)</a>,
        icon: "./Assets/Images/Party Logo/Rise-Mzansi.png",
        date: "08/02/2024",
        responsibility: [""],
    },
    {
        id: 37,
        title: <a href="https://sizweummahnation.wordpress.com/">Sizwe Ummah Nation (SUN)</a>,
        icon: "./Assets/Images/Party Logo/SUN.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 38,
        title: "South African Rainbow Alliance (SARA)",
        icon: "./Assets/Images/Party Logo/SARA.jpg",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 39,
        title: <a href="https://mkparty.org.za/">uMkhonto weSizwe (MK)</a>,
        icon: "./Assets/Images/Party Logo/MK.png",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 40,
        title: <a href="https://www.uat2023.org/">United Africans Transformation (UAT) </a>,
        icon: "",
        date: "15/03/2024",
        responsibility: [""],
    },
    {
        id: 41,
        title: <a href="https://udm.org.za/">United Democratic Movement (UDM)</a>,
        icon: "./Assets/Images/Party Logo/UDM.png",
        date: "02/03/2024",
        responsibility: [""],
    },
    {
        id: 42,
        title: <a href="https://www.vfplus.org.za/">Freedom Front Plus (FF+)</a>,
        icon: "./Assets/Images/Party Logo/FF+.png",
        date: "02/03/2024",
        responsibility: [""],
    },
    {
        id: 43,
        title: "Xiluva",
        icon: "./Assets/Images/Party Logo/Xiluva.jfif",
        date: "15/03/2024",
        responsibility: [""],
    },
]

export const gauteng = GAUTENG.map(data => 
    <li key={data.id}>
      <p>{data.title}</p>
    </li>
  )